/**
 *
 * $Id$
 */
package courseScheduling.validation;

import courseScheduling.Instructor;
import courseScheduling.Room;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link courseScheduling.Course}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CourseValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDuration(int value);

	boolean validateDuration(String value);
	boolean validateClassLimit(int value);
	boolean validateInstructors(EList<Instructor> value);
	boolean validateRoom(Room value);
}
