/**
 *
 * $Id$
 */
package courseScheduling.validation;

import courseScheduling.Day_column;
import courseScheduling.SubTimetable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link courseScheduling.SubTimetable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubTimetableValidator {
	boolean validate();

	boolean validateClassNumber(int value);
	boolean validateWeekday(EList<Day_column> value);
	boolean validateNoCollision(SubTimetable value);
}
