/**
 *
 * $Id$
 */
package courseScheduling.validation;

import courseScheduling.Day_column;
import courseScheduling.SubTimetable;
import courseScheduling.Timetable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link courseScheduling.Timetable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimetableValidator {
	boolean validate();

	boolean validateTimetables(EList<SubTimetable> value);

	boolean validateClassNmber(int value);
	boolean validateWeekday(EList<Day_column> value);
	boolean validateNoCollision(Timetable value);
}
